[project]
name = "04-02"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agno>=1.0.5",
    "exa-py>=1.8.7",
    "google-generativeai>=0.8.4",
    "openai>=1.61.0",
    "phidata>=2.7.10",
    "pip>=25.0",
]
